---
title: "About me"
---

My initial training is in experimental psychology. I have specialized in research at the intersection of neuroscience and machine learning. My work focuses on statistical modeling of cognitive & clinical outcomes from brain data i.e. electroencephalography (EEG), magnetoencephalography (MEG), magnetic resonance imaging (MRI) and heterogeneous biomedical data.

In my previous position at the French National Institute for Research in Digital Science and Technology (Inria Saclay-Île-de-France / Paris), I have developed machine learning aproaches for translating insights from laborary research and population modeling to clinical applications.

In my current role at the Roche Innovation Center Basel, I work on assessing the impact of novel compounds on brain dynamics and clinical outcomes by applying knowledge, tools and resources resulting from my research.


## Education

__Université Paris-Cité__, Paris, France | 
Habilitation à Diriger des Recherches (HDR), Médecine | 2021 - 2022

__University of Cologne__, Germany |
PhD, Psychology | 2011 - 2015

__University of Giessen__, Germany |
Diploma, Psychology | 2003 - 2010

## Experience

__Roche Pharma Research & Early Development__, Basel, Switzerland | Biomarker & Experimental Medicine Leader | 2021 - present

__Inria Saclay__, Paris, France | Research Scientist | 2017 - 2021

__CEA NeuroSpin, Paris Brain Institute (ICM)__, France | Postdoc | 2014 - 2016

__Jülich Research Center, University Hospital Cologne__, Germany | PhD student | 2011 - 2014

__Max-Planck Institute for Evolutionary Anthropology__, Leipzig, Germany | Intern | 2007 - 2009
<!-- 
## PhD Students -->


